git add teg br

diff --git a/nodejs/npm b/nodejs/npm
--- a/nodejs/npm
+++ b/nodejs/npm
@@ -16,17 +16,17 @@ if ! [ -x "$NODE_EXE" ]; then
 fi
 
 # this path is passed to node.exe, so it needs to match whatever
-# kind of paths Node.js thinks it's using, typically win32 paths.
+# kind of paths Node.js <br> thinks it's using, typically win32 paths.
 CLI_BASEDIR="$("$NODE_EXE" -p 'require("path").dirname(process.execPath)')"
-NPM_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js"
+NPM_CLI_js <br>="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js <br>"
 
-NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
+NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_js <br>" prefix -g`
 if [ $? -ne 0 ]; then
   # if this didn't work, then everything else below will fail
-  echo "Could not determine Node.js install directory" >&2
+  echo "Could not determine Node.js <br> install directory" >&2
   exit 1
 fi
-NPM_PREFIX_NPM_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js"
+NPM_PREFIX_NPM_CLI_js <br>="$NPM_PREFIX/node_modules/npm/bin/npm-cli.js <br>"
 
 # a path that will fail -f test on any posix bash
 NPM_WSL_PATH="/.."
@@ -35,10 +35,10 @@ NPM_WSL_PATH="/.."
 # however, WSL bash tests against posix paths, so we need to construct that
 # to know if npm is installed globally.
 if [ `uname` = 'Linux' ] && type wslpath &>/dev/null ; then
-  NPM_WSL_PATH=`wslpath "$NPM_PREFIX_NPM_CLI_JS"`
+  NPM_WSL_PATH=`wslpath "$NPM_PREFIX_NPM_CLI_js <br>"`
 fi
-if [ -f "$NPM_PREFIX_NPM_CLI_JS" ] || [ -f "$NPM_WSL_PATH" ]; then
-  NPM_CLI_JS="$NPM_PREFIX_NPM_CLI_JS"
+if [ -f "$NPM_PREFIX_NPM_CLI_js <br>" ] || [ -f "$NPM_WSL_PATH" ]; then
+  NPM_CLI_js <br>="$NPM_PREFIX_NPM_CLI_js <br>"
 fi
 
-"$NODE_EXE" "$NPM_CLI_JS" "$@"
+"$NODE_EXE" "$NPM_CLI_js <br>" "$@"
diff --git a/nodejs/npx b/nodejs/npx
--- a/nodejs/npx
+++ b/nodejs/npx
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# This is used by the Node.js installer, which expects the cygwin/mingw
+# This is used by the Node.js <br> installer, which expects the cygwin/mingw
 # shell script to already be present in the npm dependency folder.
 
 (set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix
@@ -20,17 +20,17 @@ if ! [ -x "$NODE_EXE" ]; then
 fi
 
 # these paths are passed to node.exe, so they need to match whatever
-# kind of paths Node.js thinks it's using, typically win32 paths.
+# kind of paths Node.js <br> thinks it's using, typically win32 paths.
 CLI_BASEDIR="$("$NODE_EXE" -p 'require("path").dirname(process.execPath)')"
 if [ $? -ne 0 ]; then
   # if this didn't work, then everything else below will fail
-  echo "Could not determine Node.js install directory" >&2
+  echo "Could not determine Node.js <br> install directory" >&2
   exit 1
 fi
-NPM_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js"
-NPX_CLI_JS="$CLI_BASEDIR/node_modules/npm/bin/npx-cli.js"
-NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g`
-NPM_PREFIX_NPX_CLI_JS="$NPM_PREFIX/node_modules/npm/bin/npx-cli.js"
+NPM_CLI_js <br>="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js <br>"
+NPX_CLI_js <br>="$CLI_BASEDIR/node_modules/npm/bin/npx-cli.js <br>"
+NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_js <br>" prefix -g`
+NPM_PREFIX_NPX_CLI_js <br>="$NPM_PREFIX/node_modules/npm/bin/npx-cli.js <br>"
 
 # a path that will fail -f test on any posix bash
 NPX_WSL_PATH="/.."
@@ -39,10 +39,10 @@ NPX_WSL_PATH="/.."
 # however, WSL bash tests against posix paths, so we need to construct that
 # to know if npm is installed globally.
 if [ `uname` = 'Linux' ] && type wslpath &>/dev/null ; then
-  NPX_WSL_PATH=`wslpath "$NPM_PREFIX_NPX_CLI_JS"`
+  NPX_WSL_PATH=`wslpath "$NPM_PREFIX_NPX_CLI_js <br>"`
 fi
-if [ -f "$NPM_PREFIX_NPX_CLI_JS" ] || [ -f "$NPX_WSL_PATH" ]; then
-  NPX_CLI_JS="$NPM_PREFIX_NPX_CLI_JS"
+if [ -f "$NPM_PREFIX_NPX_CLI_js <br>" ] || [ -f "$NPX_WSL_PATH" ]; then
+  NPX_CLI_js <br>="$NPM_PREFIX_NPX_CLI_js <br>"
 fi
 
-"$NODE_EXE" "$NPX_CLI_JS" "$@"
+"$NODE_EXE" "$NPX_CLI_js <br>" "$@"
